/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 */
package vitaminc.ui;

import java.lang.reflect.Field;
import javax.swing.ToolTipManager;
import vitaminc.Controller;
import vitaminc.Main;
import vitaminc.Util;

/**
 *
 * @author Iulian Goriac <iulian.goriac@gmail.com>
 */
public class MainWindow extends javax.swing.JFrame {

    public static final String DEFAULT_TITLE = "Vitamin C";
    private Controller controller;

    public void setController(Controller controller) {
        this.controller = controller;
    }

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        setTitle(DEFAULT_TITLE);
        ToolTipManager.sharedInstance().setInitialDelay(750);
        ToolTipManager.sharedInstance().setDismissDelay(100000);
    }

    public void initializeToolButtons() {
        for (Field field : getClass().getDeclaredFields()) {
            Object fieldObject;
            try {
                fieldObject = field.get(this);
                if (fieldObject instanceof ToolButton) {
                    ((ToolButton) fieldObject).initialize(controller);
                }
            } catch (Exception ex) {
                Main.reportException(ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionsPanel = new javax.swing.JPanel();
        openButton = new javax.swing.JButton();
        openButton1 = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        toolboxPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        toolButton1 = new vitaminc.ui.ToolButton();
        toolButton2 = new vitaminc.ui.ToolButton();
        toolButton3 = new vitaminc.ui.ToolButton();
        toolButton4 = new vitaminc.ui.ToolButton();
        toolButton5 = new vitaminc.ui.ToolButton();
        toolButton6 = new vitaminc.ui.ToolButton();
        toolButton7 = new vitaminc.ui.ToolButton();
        toolButton8 = new vitaminc.ui.ToolButton();
        toolButton9 = new vitaminc.ui.ToolButton();
        toolButton10 = new vitaminc.ui.ToolButton();
        toolButton11 = new vitaminc.ui.ToolButton();
        toolButton12 = new vitaminc.ui.ToolButton();
        toolButton13 = new vitaminc.ui.ToolButton();
        toolButton14 = new vitaminc.ui.ToolButton();
        toolButton15 = new vitaminc.ui.ToolButton();
        toolButton44 = new vitaminc.ui.ToolButton();
        jPanel9 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        toolButton16 = new vitaminc.ui.ToolButton();
        toolButton31 = new vitaminc.ui.ToolButton();
        toolButton32 = new vitaminc.ui.ToolButton();
        toolButton33 = new vitaminc.ui.ToolButton();
        toolButton34 = new vitaminc.ui.ToolButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        toolButton35 = new vitaminc.ui.ToolButton();
        toolButton36 = new vitaminc.ui.ToolButton();
        toolButton37 = new vitaminc.ui.ToolButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        toolButton38 = new vitaminc.ui.ToolButton();
        toolButton39 = new vitaminc.ui.ToolButton();
        toolButton40 = new vitaminc.ui.ToolButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        toolButton41 = new vitaminc.ui.ToolButton();
        toolButton42 = new vitaminc.ui.ToolButton();
        toolButton43 = new vitaminc.ui.ToolButton();
        jPanel10 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        toolButton25 = new vitaminc.ui.ToolButton();
        toolButton26 = new vitaminc.ui.ToolButton();
        toolButton69 = new vitaminc.ui.ToolButton();
        toolButton68 = new vitaminc.ui.ToolButton();
        toolButton70 = new vitaminc.ui.ToolButton();
        toolButton71 = new vitaminc.ui.ToolButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        toolButton17 = new vitaminc.ui.ToolButton();
        toolButton45 = new vitaminc.ui.ToolButton();
        toolButton46 = new vitaminc.ui.ToolButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        toolButton49 = new vitaminc.ui.ToolButton();
        toolButton50 = new vitaminc.ui.ToolButton();
        toolButton51 = new vitaminc.ui.ToolButton();
        toolButton52 = new vitaminc.ui.ToolButton();
        toolButton53 = new vitaminc.ui.ToolButton();
        toolButton54 = new vitaminc.ui.ToolButton();
        jPanel6 = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        toolButton24 = new vitaminc.ui.ToolButton();
        toolButton66 = new vitaminc.ui.ToolButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        toolButton67 = new vitaminc.ui.ToolButton();
        toolButton27 = new vitaminc.ui.ToolButton();
        toolButton28 = new vitaminc.ui.ToolButton();
        toolButton29 = new vitaminc.ui.ToolButton();
        toolButton30 = new vitaminc.ui.ToolButton();
        toolButton47 = new vitaminc.ui.ToolButton();
        toolButton48 = new vitaminc.ui.ToolButton();
        toolButton55 = new vitaminc.ui.ToolButton();
        toolButton56 = new vitaminc.ui.ToolButton();
        toolButton57 = new vitaminc.ui.ToolButton();
        toolButton58 = new vitaminc.ui.ToolButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        toolButton18 = new vitaminc.ui.ToolButton();
        toolButton19 = new vitaminc.ui.ToolButton();
        toolButton20 = new vitaminc.ui.ToolButton();
        toolButton21 = new vitaminc.ui.ToolButton();
        toolButton22 = new vitaminc.ui.ToolButton();
        toolButton23 = new vitaminc.ui.ToolButton();
        jPanel11 = new javax.swing.JPanel();
        jToolBar8 = new javax.swing.JToolBar();
        toolButton82 = new vitaminc.ui.ToolButton();
        toolButton83 = new vitaminc.ui.ToolButton();
        toolButton84 = new vitaminc.ui.ToolButton();
        jPanel12 = new javax.swing.JPanel();
        jToolBar9 = new javax.swing.JToolBar();
        toolButton96 = new vitaminc.ui.ToolButton();
        toolButton97 = new vitaminc.ui.ToolButton();
        toolButton98 = new vitaminc.ui.ToolButton();
        toolButton99 = new vitaminc.ui.ToolButton();
        toolButton100 = new vitaminc.ui.ToolButton();
        toolButton101 = new vitaminc.ui.ToolButton();
        toolButton102 = new vitaminc.ui.ToolButton();
        toolButton103 = new vitaminc.ui.ToolButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        toolButton105 = new vitaminc.ui.ToolButton();
        toolButton106 = new vitaminc.ui.ToolButton();
        toolButton107 = new vitaminc.ui.ToolButton();
        jPanel8 = new javax.swing.JPanel();
        jToolBar10 = new javax.swing.JToolBar();
        toolButton111 = new vitaminc.ui.ToolButton();
        toolButton112 = new vitaminc.ui.ToolButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        toolButton113 = new vitaminc.ui.ToolButton();
        toolButton114 = new vitaminc.ui.ToolButton();
        toolButton115 = new vitaminc.ui.ToolButton();
        toolButton116 = new vitaminc.ui.ToolButton();
        toolButton117 = new vitaminc.ui.ToolButton();
        toolButton118 = new vitaminc.ui.ToolButton();
        toolButton119 = new vitaminc.ui.ToolButton();
        toolButton120 = new vitaminc.ui.ToolButton();
        toolButton121 = new vitaminc.ui.ToolButton();
        toolButton122 = new vitaminc.ui.ToolButton();
        toolButton123 = new vitaminc.ui.ToolButton();
        shapesPanel = new javax.swing.JPanel();
        jToolBar7 = new javax.swing.JToolBar();
        toolButton59 = new vitaminc.ui.ToolButton();
        toolButton60 = new vitaminc.ui.ToolButton();
        toolButton63 = new vitaminc.ui.ToolButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        toolButton72 = new vitaminc.ui.ToolButton();
        toolButton73 = new vitaminc.ui.ToolButton();
        toolButton74 = new vitaminc.ui.ToolButton();
        toolButton75 = new vitaminc.ui.ToolButton();
        toolButton76 = new vitaminc.ui.ToolButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        fileSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        editSeparator2 = new javax.swing.JPopupMenu.Separator();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        editSeparator1 = new javax.swing.JPopupMenu.Separator();
        findMenuItem = new javax.swing.JMenuItem();
        nextMenuItem = new javax.swing.JMenuItem();
        programMenu = new javax.swing.JMenu();
        windowMenu = new javax.swing.JMenu();
        windowSeparator1 = new javax.swing.JPopupMenu.Separator();
        arrangeMenuItem = new javax.swing.JMenuItem();
        resetWindowsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jythonMenuItem = new javax.swing.JMenuItem();
        jythonDocMenuItem = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        logoMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vitamin C");
        setIconImage(Resources.mainWindowIcon);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        actionsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/read.png"))); // NOI18N
        openButton.setToolTipText("Read Program from File (Ctrl + R)");
        openButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        openButton.setPreferredSize(new java.awt.Dimension(32, 32));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        openButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/write.png"))); // NOI18N
        openButton1.setToolTipText("Write Program to File (Ctrl + W)");
        openButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        openButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        openButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButton1ActionPerformed(evt);
            }
        });

        programButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/program.png"))); // NOI18N
        programButton.setToolTipText("Show/hide Program Window (F2)");
        programButton.setMargin(new java.awt.Insets(1, 1, 1, 1));
        programButton.setPreferredSize(new java.awt.Dimension(32, 32));
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });

        drawingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drawing.png"))); // NOI18N
        drawingButton.setToolTipText("Show/hide Drawing Window (F4)");
        drawingButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        drawingButton.setPreferredSize(new java.awt.Dimension(32, 32));
        drawingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawingButtonActionPerformed(evt);
            }
        });

        runButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/run.png"))); // NOI18N
        runButton.setToolTipText("Run Program (F5)");
        runButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        runButton.setPreferredSize(new java.awt.Dimension(32, 32));
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/stop.png"))); // NOI18N
        stopButton.setToolTipText("Stop Running the Program");
        stopButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        stopButton.setPreferredSize(new java.awt.Dimension(32, 32));
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/new.png"))); // NOI18N
        newButton.setToolTipText("New Program (Ctrl + N)");
        newButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        newButton.setPreferredSize(new java.awt.Dimension(32, 32));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        consoleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/console.png"))); // NOI18N
        consoleButton.setToolTipText("Show/hide Console Window (F3)");
        consoleButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        consoleButton.setPreferredSize(new java.awt.Dimension(32, 32));
        consoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleButtonActionPerformed(evt);
            }
        });

        arrangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/arrange.png"))); // NOI18N
        arrangeButton.setToolTipText("Arrange Visible Windows");
        arrangeButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        arrangeButton.setPreferredSize(new java.awt.Dimension(32, 32));
        arrangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionsPanelLayout = new javax.swing.GroupLayout(actionsPanel);
        actionsPanel.setLayout(actionsPanelLayout);
        actionsPanelLayout.setHorizontalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionsPanelLayout.createSequentialGroup()
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actionsPanelLayout.createSequentialGroup()
                        .addComponent(programButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arrangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actionsPanelLayout.setVerticalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(consoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(drawingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arrangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(programButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        toolboxPane.setForeground(java.awt.SystemColor.controlDkShadow);
        toolboxPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        toolboxPane.setFont(new java.awt.Font("Tahoma", 1, 11));

        jTabbedPane1.setForeground(java.awt.SystemColor.controlDkShadow);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 2, 10));

        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton1.setText("forward");
        toolButton1.setFocusable(false);
        toolButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton1);

        toolButton2.setText("backward");
        toolButton2.setFocusable(false);
        toolButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton2);

        toolButton3.setText("left");
        toolButton3.setFocusable(false);
        toolButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton3);

        toolButton4.setText("right");
        toolButton4.setFocusable(false);
        toolButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton4);

        toolButton5.setText("goto");
        toolButton5.setFocusable(false);
        toolButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton5);

        toolButton6.setText("setx");
        toolButton6.setFocusable(false);
        toolButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton6);

        toolButton7.setText("sety");
        toolButton7.setFocusable(false);
        toolButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton7);

        toolButton8.setText("setheading");
        toolButton8.setFocusable(false);
        toolButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton8);

        toolButton9.setText("home");
        toolButton9.setFocusable(false);
        toolButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton9);

        toolButton10.setText("circle");
        toolButton10.setFocusable(false);
        toolButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton10);

        toolButton11.setText("dot");
        toolButton11.setFocusable(false);
        toolButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton11);

        toolButton12.setText("stamp");
        toolButton12.setFocusable(false);
        toolButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton12);

        toolButton13.setText("clearstamp");
        toolButton13.setFocusable(false);
        toolButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton13);

        toolButton14.setText("clearstamps");
        toolButton14.setFocusable(false);
        toolButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton14);

        toolButton15.setText("undo");
        toolButton15.setFocusable(false);
        toolButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton15);

        toolButton44.setText("speed");
        toolButton44.setFocusable(false);
        toolButton44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton44.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toolButton44);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Move & Draw ", jPanel2);

        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);
        jToolBar4.setBorderPainted(false);
        jToolBar4.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton16.setText("pendown");
        toolButton16.setFocusable(false);
        toolButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton16);

        toolButton31.setText("penup");
        toolButton31.setFocusable(false);
        toolButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton31);

        toolButton32.setText("pensize");
        toolButton32.setFocusable(false);
        toolButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton32.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton32);

        toolButton33.setText("pen");
        toolButton33.setFocusable(false);
        toolButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton33.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton33);

        toolButton34.setText("isdown");
        toolButton34.setFocusable(false);
        toolButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton34.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton34);
        jToolBar4.add(jSeparator2);

        toolButton35.setText("color");
        toolButton35.setFocusable(false);
        toolButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton35.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton35);

        toolButton36.setText("pencolor");
        toolButton36.setFocusable(false);
        toolButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton36.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton36);

        toolButton37.setText("fillcolor");
        toolButton37.setFocusable(false);
        toolButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton37.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton37);
        jToolBar4.add(jSeparator3);

        toolButton38.setText("fill");
        toolButton38.setFocusable(false);
        toolButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton38.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton38);

        toolButton39.setText("begin_fill");
        toolButton39.setFocusable(false);
        toolButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton39.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton39);

        toolButton40.setText("end_fill");
        toolButton40.setFocusable(false);
        toolButton40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton40.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton40);
        jToolBar4.add(jSeparator4);

        toolButton41.setText("reset");
        toolButton41.setFocusable(false);
        toolButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton41.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton41);

        toolButton42.setText("clear");
        toolButton42.setFocusable(false);
        toolButton42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton42.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton42);

        toolButton43.setText("write");
        toolButton43.setFocusable(false);
        toolButton43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton43.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(toolButton43);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pen", jPanel9);

        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);
        jToolBar5.setBorderPainted(false);
        jToolBar5.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton25.setText("position");
        toolButton25.setFocusable(false);
        toolButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton25);

        toolButton26.setText("towards");
        toolButton26.setFocusable(false);
        toolButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton26);

        toolButton69.setText("xcor");
        toolButton69.setFocusable(false);
        toolButton69.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton69.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton69);

        toolButton68.setText("ycor");
        toolButton68.setFocusable(false);
        toolButton68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton68.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton68);

        toolButton70.setText("heading");
        toolButton70.setFocusable(false);
        toolButton70.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton70.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton70);

        toolButton71.setText("distance");
        toolButton71.setFocusable(false);
        toolButton71.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton71.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton71);
        jToolBar5.add(jSeparator5);

        toolButton17.setText("showturtle");
        toolButton17.setFocusable(false);
        toolButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton17);

        toolButton45.setText("hideturtle");
        toolButton45.setFocusable(false);
        toolButton45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton45.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton45);

        toolButton46.setText("isvisible");
        toolButton46.setFocusable(false);
        toolButton46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton46.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton46);
        jToolBar5.add(jSeparator6);

        toolButton49.setText("shape");
        toolButton49.setFocusable(false);
        toolButton49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton49.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton49);

        toolButton50.setText("resizemode");
        toolButton50.setFocusable(false);
        toolButton50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton50.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton50);

        toolButton51.setText("shapesize");
        toolButton51.setFocusable(false);
        toolButton51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton51.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton51);

        toolButton52.setText("settiltangle");
        toolButton52.setFocusable(false);
        toolButton52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton52.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton52);

        toolButton53.setText("tiltangle");
        toolButton53.setFocusable(false);
        toolButton53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton53.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton53);

        toolButton54.setText("tilt");
        toolButton54.setFocusable(false);
        toolButton54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton54.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(toolButton54);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("State", jPanel10);

        jToolBar6.setFloatable(false);
        jToolBar6.setRollover(true);
        jToolBar6.setBorderPainted(false);
        jToolBar6.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton24.setText("degrees");
        toolButton24.setFocusable(false);
        toolButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton24);

        toolButton66.setText("radians");
        toolButton66.setFocusable(false);
        toolButton66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton66.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton66);
        jToolBar6.add(jSeparator7);

        toolButton67.setText("begin_poly");
        toolButton67.setFocusable(false);
        toolButton67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton67.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton67);

        toolButton27.setText("end_poly");
        toolButton27.setFocusable(false);
        toolButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton27);

        toolButton28.setText("get_poly");
        toolButton28.setFocusable(false);
        toolButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton28);

        toolButton29.setText("clone");
        toolButton29.setFocusable(false);
        toolButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton29);

        toolButton30.setText("getturtle");
        toolButton30.setFocusable(false);
        toolButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton30);

        toolButton47.setText("getscreen");
        toolButton47.setFocusable(false);
        toolButton47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton47.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton47);

        toolButton48.setText("setundobuffer");
        toolButton48.setFocusable(false);
        toolButton48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton48.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton48);

        toolButton55.setText("undobufferentries");
        toolButton55.setFocusable(false);
        toolButton55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton55.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton55);

        toolButton56.setText("tracer");
        toolButton56.setFocusable(false);
        toolButton56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton56.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton56);

        toolButton57.setText("window_width");
        toolButton57.setFocusable(false);
        toolButton57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton57.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton57);

        toolButton58.setText("window_height");
        toolButton58.setFocusable(false);
        toolButton58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton58.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(toolButton58);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Special functions", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Move & Draw");

        toolboxPane.addTab("Turtle", jPanel1);

        jTabbedPane2.setForeground(java.awt.SystemColor.controlDkShadow);
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 2, 10));

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);
        jToolBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton18.setText("bgcolor");
        toolButton18.setFocusable(false);
        toolButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton18);

        toolButton19.setText("bgpic");
        toolButton19.setFocusable(false);
        toolButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton19);

        toolButton20.setText("clear");
        toolButton20.setFocusable(false);
        toolButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton20);

        toolButton21.setText("reset");
        toolButton21.setFocusable(false);
        toolButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton21);

        toolButton22.setText("screensize");
        toolButton22.setFocusable(false);
        toolButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton22);

        toolButton23.setText("setworldcoordinates");
        toolButton23.setFocusable(false);
        toolButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toolButton23);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Window control", jPanel3);

        jToolBar8.setFloatable(false);
        jToolBar8.setRollover(true);
        jToolBar8.setBorderPainted(false);
        jToolBar8.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton82.setText("delay");
        toolButton82.setFocusable(false);
        toolButton82.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton82.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar8.add(toolButton82);

        toolButton83.setText("tracer");
        toolButton83.setFocusable(false);
        toolButton83.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton83.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar8.add(toolButton83);

        toolButton84.setText("update");
        toolButton84.setFocusable(false);
        toolButton84.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton84.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar8.add(toolButton84);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar8, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Animation control", jPanel11);

        jToolBar9.setFloatable(false);
        jToolBar9.setRollover(true);
        jToolBar9.setBorderPainted(false);
        jToolBar9.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton96.setText("mode");
        toolButton96.setFocusable(false);
        toolButton96.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton96.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton96);

        toolButton97.setText("colormode");
        toolButton97.setFocusable(false);
        toolButton97.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton97.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton97);

        toolButton98.setText("getcanvas");
        toolButton98.setFocusable(false);
        toolButton98.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton98.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton98);

        toolButton99.setText("getshapes");
        toolButton99.setFocusable(false);
        toolButton99.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton99.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton99);

        toolButton100.setText("register_shape");
        toolButton100.setFocusable(false);
        toolButton100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton100.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton100);

        toolButton101.setText("turtles");
        toolButton101.setFocusable(false);
        toolButton101.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton101.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton101);

        toolButton102.setText("window_height");
        toolButton102.setFocusable(false);
        toolButton102.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton102.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton102);

        toolButton103.setText("window_width");
        toolButton103.setFocusable(false);
        toolButton103.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton103.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton103);
        jToolBar9.add(jSeparator12);

        toolButton105.setText("title");
        toolButton105.setFocusable(false);
        toolButton105.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton105.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton105);

        toolButton106.setText("setup");
        toolButton106.setFocusable(false);
        toolButton106.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton106.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton106);

        toolButton107.setText("bye");
        toolButton107.setFocusable(false);
        toolButton107.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton107.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar9.add(toolButton107);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar9, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Settings and special functions", jPanel12);

        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);
        jToolBar10.setBorderPainted(false);
        jToolBar10.setMargin(new java.awt.Insets(2, 2, 2, 2));

        toolButton111.setText("degrees");
        toolButton111.setFocusable(false);
        toolButton111.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton111.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton111);

        toolButton112.setText("radians");
        toolButton112.setFocusable(false);
        toolButton112.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton112.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton112);
        jToolBar10.add(jSeparator13);

        toolButton113.setText("begin_poly");
        toolButton113.setFocusable(false);
        toolButton113.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton113.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton113);

        toolButton114.setText("end_poly");
        toolButton114.setFocusable(false);
        toolButton114.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton114.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton114);

        toolButton115.setText("get_poly");
        toolButton115.setFocusable(false);
        toolButton115.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton115.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton115);

        toolButton116.setText("clone");
        toolButton116.setFocusable(false);
        toolButton116.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton116.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton116);

        toolButton117.setText("getturtle");
        toolButton117.setFocusable(false);
        toolButton117.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton117.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton117);

        toolButton118.setText("getscreen");
        toolButton118.setFocusable(false);
        toolButton118.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton118.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton118);

        toolButton119.setText("setundobuffer");
        toolButton119.setFocusable(false);
        toolButton119.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton119.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton119);

        toolButton120.setText("undobufferentries");
        toolButton120.setFocusable(false);
        toolButton120.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton120.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton120);

        toolButton121.setText("tracer");
        toolButton121.setFocusable(false);
        toolButton121.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton121.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton121);

        toolButton122.setText("window_width");
        toolButton122.setFocusable(false);
        toolButton122.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton122.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton122);

        toolButton123.setText("window_height");
        toolButton123.setFocusable(false);
        toolButton123.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton123.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar10.add(toolButton123);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar10, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Special Functions", jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE)
        );

        toolboxPane.addTab("Screen", jPanel7);

        jToolBar7.setRollover(true);
        jToolBar7.setBorderPainted(false);

        toolButton59.setText("onclick");
        toolButton59.setFocusable(false);
        toolButton59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton59.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton59);

        toolButton60.setText("onrelease");
        toolButton60.setFocusable(false);
        toolButton60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton60.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton60);

        toolButton63.setText("ondrag");
        toolButton63.setFocusable(false);
        toolButton63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton63.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton63);

        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 32767));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(8, 0));
        jToolBar7.add(jSeparator1);

        toolButton72.setText("listen");
        toolButton72.setFocusable(false);
        toolButton72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton72.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton72);

        toolButton73.setText("onkey");
        toolButton73.setFocusable(false);
        toolButton73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton73.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton73);

        toolButton74.setText("onclick");
        toolButton74.setFocusable(false);
        toolButton74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton74.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton74);

        toolButton75.setText("ontimer");
        toolButton75.setFocusable(false);
        toolButton75.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton75.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton75);

        toolButton76.setText("exitonclick");
        toolButton76.setFocusable(false);
        toolButton76.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolButton76.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar7.add(toolButton76);

        javax.swing.GroupLayout shapesPanelLayout = new javax.swing.GroupLayout(shapesPanel);
        shapesPanel.setLayout(shapesPanelLayout);
        shapesPanelLayout.setHorizontalGroup(
            shapesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        shapesPanelLayout.setVerticalGroup(
            shapesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        toolboxPane.addTab("Events", shapesPanel);

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/new.png"))); // NOI18N
        newMenuItem.setMnemonic('N');
        newMenuItem.setText("New Program");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/read.png"))); // NOI18N
        openMenuItem.setMnemonic('R');
        openMenuItem.setText("Read Program ...");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/write.png"))); // NOI18N
        saveMenuItem.setMnemonic('W');
        saveMenuItem.setText("Write Program");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('A');
        saveAsMenuItem.setText("Write Program As ...");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(fileSeparator1);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('E');
        editMenu.setText("Edit");

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setMnemonic('u');
        undoMenuItem.setText("Undo");
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setMnemonic('r');
        redoMenuItem.setText("Redo");
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(redoMenuItem);
        editMenu.add(editSeparator2);

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setMnemonic('P');
        pasteMenuItem.setText("Paste");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);
        editMenu.add(editSeparator1);

        findMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        findMenuItem.setMnemonic('F');
        findMenuItem.setText("Find...");
        findMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(findMenuItem);

        nextMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        nextMenuItem.setMnemonic('N');
        nextMenuItem.setText("Find Next");
        nextMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(nextMenuItem);

        menuBar.add(editMenu);

        programMenu.setMnemonic('p');
        programMenu.setText("Program");

        runMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        runMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/run.png"))); // NOI18N
        runMenuItem.setMnemonic('r');
        runMenuItem.setText("Run");
        runMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runMenuItemActionPerformed(evt);
            }
        });
        programMenu.add(runMenuItem);

        stopMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/stop.png"))); // NOI18N
        stopMenuItem.setMnemonic('s');
        stopMenuItem.setText("Stop");
        stopMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMenuItemActionPerformed(evt);
            }
        });
        programMenu.add(stopMenuItem);

        menuBar.add(programMenu);

        windowMenu.setMnemonic('w');
        windowMenu.setText("Window");

        programMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        programMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/program.png"))); // NOI18N
        programMenuItem.setMnemonic('p');
        programMenuItem.setText("Program Window");
        programMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(programMenuItem);

        consoleMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        consoleMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/console.png"))); // NOI18N
        consoleMenuItem.setMnemonic('m');
        consoleMenuItem.setText("Console Window");
        consoleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(consoleMenuItem);

        drawingMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        drawingMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drawing.png"))); // NOI18N
        drawingMenuItem.setMnemonic('d');
        drawingMenuItem.setText("Drawing Window");
        drawingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawingMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(drawingMenuItem);
        windowMenu.add(windowSeparator1);

        arrangeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/arrange.png"))); // NOI18N
        arrangeMenuItem.setMnemonic('a');
        arrangeMenuItem.setText("Arrange Visible Windows");
        arrangeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrangeMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(arrangeMenuItem);

        resetWindowsMenuItem.setMnemonic('r');
        resetWindowsMenuItem.setText("Reset Windows Positions");
        resetWindowsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetWindowsMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(resetWindowsMenuItem);

        menuBar.add(windowMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("Help");

        contentsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        contentsMenuItem.setMnemonic('C');
        contentsMenuItem.setText("Contents");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);
        helpMenu.add(jSeparator8);

        jythonMenuItem.setText("Jython ...");
        jythonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jythonMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(jythonMenuItem);

        jythonDocMenuItem.setText("Jython Doc ...");
        jythonDocMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jythonDocMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(jythonDocMenuItem);
        helpMenu.add(jSeparator9);

        logoMenuItem.setText("About Logo");
        logoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(logoMenuItem);

        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About Vitamin C");
        aboutMenuItem.setActionCommand("About Vitamin C");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolboxPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(toolboxPane, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        toolboxPane.getAccessibleContext().setAccessibleName("Shapes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        controller.exitApplication();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.exitApplication();
    }//GEN-LAST:event_formWindowClosing

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        controller.setProgramWindowVisible(programButton.isSelected());
    }//GEN-LAST:event_programButtonActionPerformed

    private void drawingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawingButtonActionPerformed
        controller.setDrawingWindowVisible(drawingButton.isSelected());
    }//GEN-LAST:event_drawingButtonActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        controller.readProgram();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        controller.readProgram();
    }//GEN-LAST:event_openButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        controller.newProgram();
    }//GEN-LAST:event_newButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        controller.stopProgram();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        controller.runProgram();
    }//GEN-LAST:event_runButtonActionPerformed

    private void consoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleButtonActionPerformed
        controller.setConsoleWindowVisible(consoleButton.isSelected());
    }//GEN-LAST:event_consoleButtonActionPerformed

    private void openButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButton1ActionPerformed
        controller.writeProgram();
    }//GEN-LAST:event_openButton1ActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        controller.writeProgram();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        controller.writeProgramAs();
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        controller.newProgram();
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void runMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runMenuItemActionPerformed
        controller.runProgram();
    }//GEN-LAST:event_runMenuItemActionPerformed

    private void stopMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMenuItemActionPerformed
        controller.stopProgram();
    }//GEN-LAST:event_stopMenuItemActionPerformed

    private void programMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programMenuItemActionPerformed
        controller.toggleProgramWindowVisible();
    }//GEN-LAST:event_programMenuItemActionPerformed

    private void consoleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleMenuItemActionPerformed
        controller.toggleConsoleWindowVisible();
    }//GEN-LAST:event_consoleMenuItemActionPerformed

    private void drawingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawingMenuItemActionPerformed
        controller.toggleDrawingWindowVisible();
    }//GEN-LAST:event_drawingMenuItemActionPerformed

    private void resetWindowsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetWindowsMenuItemActionPerformed
        controller.resetWindowsPositions();
    }//GEN-LAST:event_resetWindowsMenuItemActionPerformed

    private void arrangeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrangeMenuItemActionPerformed
        controller.arrangeVisibleWindows();
    }//GEN-LAST:event_arrangeMenuItemActionPerformed

    private void arrangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrangeButtonActionPerformed
        controller.arrangeVisibleWindows();
    }//GEN-LAST:event_arrangeButtonActionPerformed

    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
        controller.undo();
    }//GEN-LAST:event_undoMenuItemActionPerformed

    private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
        controller.redo();
    }//GEN-LAST:event_redoMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        controller.cut();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        controller.copy();
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        controller.paste();
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void findMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMenuItemActionPerformed
        controller.find();
    }//GEN-LAST:event_findMenuItemActionPerformed

    private void nextMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMenuItemActionPerformed
        controller.findNext();
    }//GEN-LAST:event_nextMenuItemActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        controller.iconify();
    }//GEN-LAST:event_formWindowIconified

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        controller.deiconify();
    }//GEN-LAST:event_formWindowDeiconified

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controller.initialize();
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int height = getMinimumSize().height;
        if (getHeight() > height) {
            int width = getWidth();
            setSize(width, height);
        }
        if (getY() < 0) {
            setLocation(getX(), 0);
        }
    }//GEN-LAST:event_formComponentResized

    private void jythonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jythonMenuItemActionPerformed
        Util.openWebPageInSystemBrowser(Util.JYTHON_HOME_PAGE);
    }//GEN-LAST:event_jythonMenuItemActionPerformed

    private void logoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoMenuItemActionPerformed
        Util.openWebPageInSystemBrowser(Util.LOGO_HOME_PAGE);
    }//GEN-LAST:event_logoMenuItemActionPerformed

    private void jythonDocMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jythonDocMenuItemActionPerformed
        Util.openWebPageInSystemBrowser(Util.JYTHON_DOC_PAGE);
    }//GEN-LAST:event_jythonDocMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        controller.about();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        Util.openWebHelp();
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel actionsPanel;
    public final javax.swing.JButton arrangeButton = new javax.swing.JButton();
    private javax.swing.JMenuItem arrangeMenuItem;
    public final javax.swing.JToggleButton consoleButton = new javax.swing.JToggleButton();
    public final javax.swing.JMenuItem consoleMenuItem = new javax.swing.JMenuItem();
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public final javax.swing.JToggleButton drawingButton = new javax.swing.JToggleButton();
    public final javax.swing.JMenuItem drawingMenuItem = new javax.swing.JMenuItem();
    private javax.swing.JMenu editMenu;
    private javax.swing.JPopupMenu.Separator editSeparator1;
    private javax.swing.JPopupMenu.Separator editSeparator2;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileSeparator1;
    private javax.swing.JMenuItem findMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JToolBar jToolBar9;
    private javax.swing.JMenuItem jythonDocMenuItem;
    private javax.swing.JMenuItem jythonMenuItem;
    private javax.swing.JMenuItem logoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton newButton;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem nextMenuItem;
    private javax.swing.JButton openButton;
    private javax.swing.JButton openButton1;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    public final javax.swing.JToggleButton programButton = new javax.swing.JToggleButton();
    private javax.swing.JMenu programMenu;
    public final javax.swing.JMenuItem programMenuItem = new javax.swing.JMenuItem();
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem resetWindowsMenuItem;
    public final javax.swing.JButton runButton = new javax.swing.JButton();
    public final javax.swing.JMenuItem runMenuItem = new javax.swing.JMenuItem();
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPanel shapesPanel;
    public final javax.swing.JButton stopButton = new javax.swing.JButton();
    public final javax.swing.JMenuItem stopMenuItem = new javax.swing.JMenuItem();
    private vitaminc.ui.ToolButton toolButton1;
    private vitaminc.ui.ToolButton toolButton10;
    private vitaminc.ui.ToolButton toolButton100;
    private vitaminc.ui.ToolButton toolButton101;
    private vitaminc.ui.ToolButton toolButton102;
    private vitaminc.ui.ToolButton toolButton103;
    private vitaminc.ui.ToolButton toolButton105;
    private vitaminc.ui.ToolButton toolButton106;
    private vitaminc.ui.ToolButton toolButton107;
    private vitaminc.ui.ToolButton toolButton11;
    private vitaminc.ui.ToolButton toolButton111;
    private vitaminc.ui.ToolButton toolButton112;
    private vitaminc.ui.ToolButton toolButton113;
    private vitaminc.ui.ToolButton toolButton114;
    private vitaminc.ui.ToolButton toolButton115;
    private vitaminc.ui.ToolButton toolButton116;
    private vitaminc.ui.ToolButton toolButton117;
    private vitaminc.ui.ToolButton toolButton118;
    private vitaminc.ui.ToolButton toolButton119;
    private vitaminc.ui.ToolButton toolButton12;
    private vitaminc.ui.ToolButton toolButton120;
    private vitaminc.ui.ToolButton toolButton121;
    private vitaminc.ui.ToolButton toolButton122;
    private vitaminc.ui.ToolButton toolButton123;
    private vitaminc.ui.ToolButton toolButton13;
    private vitaminc.ui.ToolButton toolButton14;
    private vitaminc.ui.ToolButton toolButton15;
    private vitaminc.ui.ToolButton toolButton16;
    private vitaminc.ui.ToolButton toolButton17;
    private vitaminc.ui.ToolButton toolButton18;
    private vitaminc.ui.ToolButton toolButton19;
    private vitaminc.ui.ToolButton toolButton2;
    private vitaminc.ui.ToolButton toolButton20;
    private vitaminc.ui.ToolButton toolButton21;
    private vitaminc.ui.ToolButton toolButton22;
    private vitaminc.ui.ToolButton toolButton23;
    private vitaminc.ui.ToolButton toolButton24;
    private vitaminc.ui.ToolButton toolButton25;
    private vitaminc.ui.ToolButton toolButton26;
    private vitaminc.ui.ToolButton toolButton27;
    private vitaminc.ui.ToolButton toolButton28;
    private vitaminc.ui.ToolButton toolButton29;
    private vitaminc.ui.ToolButton toolButton3;
    private vitaminc.ui.ToolButton toolButton30;
    private vitaminc.ui.ToolButton toolButton31;
    private vitaminc.ui.ToolButton toolButton32;
    private vitaminc.ui.ToolButton toolButton33;
    private vitaminc.ui.ToolButton toolButton34;
    private vitaminc.ui.ToolButton toolButton35;
    private vitaminc.ui.ToolButton toolButton36;
    private vitaminc.ui.ToolButton toolButton37;
    private vitaminc.ui.ToolButton toolButton38;
    private vitaminc.ui.ToolButton toolButton39;
    private vitaminc.ui.ToolButton toolButton4;
    private vitaminc.ui.ToolButton toolButton40;
    private vitaminc.ui.ToolButton toolButton41;
    private vitaminc.ui.ToolButton toolButton42;
    private vitaminc.ui.ToolButton toolButton43;
    private vitaminc.ui.ToolButton toolButton44;
    private vitaminc.ui.ToolButton toolButton45;
    private vitaminc.ui.ToolButton toolButton46;
    private vitaminc.ui.ToolButton toolButton47;
    private vitaminc.ui.ToolButton toolButton48;
    private vitaminc.ui.ToolButton toolButton49;
    private vitaminc.ui.ToolButton toolButton5;
    private vitaminc.ui.ToolButton toolButton50;
    private vitaminc.ui.ToolButton toolButton51;
    private vitaminc.ui.ToolButton toolButton52;
    private vitaminc.ui.ToolButton toolButton53;
    private vitaminc.ui.ToolButton toolButton54;
    private vitaminc.ui.ToolButton toolButton55;
    private vitaminc.ui.ToolButton toolButton56;
    private vitaminc.ui.ToolButton toolButton57;
    private vitaminc.ui.ToolButton toolButton58;
    private vitaminc.ui.ToolButton toolButton59;
    private vitaminc.ui.ToolButton toolButton6;
    private vitaminc.ui.ToolButton toolButton60;
    private vitaminc.ui.ToolButton toolButton63;
    private vitaminc.ui.ToolButton toolButton66;
    private vitaminc.ui.ToolButton toolButton67;
    private vitaminc.ui.ToolButton toolButton68;
    private vitaminc.ui.ToolButton toolButton69;
    private vitaminc.ui.ToolButton toolButton7;
    private vitaminc.ui.ToolButton toolButton70;
    private vitaminc.ui.ToolButton toolButton71;
    private vitaminc.ui.ToolButton toolButton72;
    private vitaminc.ui.ToolButton toolButton73;
    private vitaminc.ui.ToolButton toolButton74;
    private vitaminc.ui.ToolButton toolButton75;
    private vitaminc.ui.ToolButton toolButton76;
    private vitaminc.ui.ToolButton toolButton8;
    private vitaminc.ui.ToolButton toolButton82;
    private vitaminc.ui.ToolButton toolButton83;
    private vitaminc.ui.ToolButton toolButton84;
    private vitaminc.ui.ToolButton toolButton9;
    private vitaminc.ui.ToolButton toolButton96;
    private vitaminc.ui.ToolButton toolButton97;
    private vitaminc.ui.ToolButton toolButton98;
    private vitaminc.ui.ToolButton toolButton99;
    private javax.swing.JTabbedPane toolboxPane;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenu windowMenu;
    private javax.swing.JPopupMenu.Separator windowSeparator1;
    // End of variables declaration//GEN-END:variables
}
